// for reference:
// https://github.com/mantinedev/mantine/blob/master/packages/%40mantine/core/src/core/MantineProvider/global.css
// https://tailwindcss.com/docs/theme#default-theme-variable-reference

import { DEFAULT_THEME } from "@mantine/core";

export function generateDefaultImports() {
	return `
/** This file is autogenerated by the script. Do not edit it manually. */
@layer theme, base, mantine, components, utilities;
@import "tailwindcss/theme.css" layer(theme);
@import "tailwindcss/preflight.css" layer(base);
@import "tailwindcss/utilities.css" layer(utilities);

@import "@mantine/core/styles.layer.css";
`;
}

/**
 * @param {import("@mantine/core").MantineTheme} theme
 */
export function generateTheme(theme = DEFAULT_THEME) {
	// check if the object is deeply equal to DEFAULT_THEME
	const isDefault = JSON.stringify(theme) === JSON.stringify(DEFAULT_THEME);

	return `
/** This file is autogenerated by the script. Do not edit it manually. */
${isDefault ? '@custom-variant dark (&:where([data-mantine-color-scheme="dark"], [data-mantine-color-scheme="dark"] *));' : ""}

@theme {
  ${
		isDefault
			? `
  /* font */
  --font-sans: var(--mantine-font-family);
  --font-mono: var(--mantine-font-family-monospace);
  --font-headings: var(--mantine-font-family-headings);

  /* colors - primary */
  --color-primary-50: rgb(from var(--mantine-primary-color-0) r g b / <alpha-value>);
  --color-primary-100: rgb(from var(--mantine-primary-color-1) r g b / <alpha-value>);
  --color-primary-200: rgb(from var(--mantine-primary-color-2) r g b / <alpha-value>);
  --color-primary-300: rgb(from var(--mantine-primary-color-3) r g b / <alpha-value>);
  --color-primary-400: rgb(from var(--mantine-primary-color-4) r g b / <alpha-value>);
  --color-primary-500: rgb(from var(--mantine-primary-color-5) r g b / <alpha-value>);
  --color-primary-600: rgb(from var(--mantine-primary-color-6) r g b / <alpha-value>);
  --color-primary-700: rgb(from var(--mantine-primary-color-7) r g b / <alpha-value>);
  --color-primary-800: rgb(from var(--mantine-primary-color-8) r g b / <alpha-value>);
  --color-primary-900: rgb(from var(--mantine-primary-color-9) r g b / <alpha-value>);
  --color-primary: rgb(from var(--mantine-primary-color-filled) r g b / <alpha-value>);

  /* colors - variant specific primary */
  --color-primary-filled: rgb(from var(--mantine-primary-color-filled) r g b / <alpha-value>);
  --color-primary-filled-hover: var(--mantine-primary-color-filled-hover);
  --color-primary-light: var(--mantine-primary-color-light);
  --color-primary-light-hover: var(--mantine-primary-color-light-hover);
  --color-primary-light-color: rgb(from var(--mantine-primary-color-light-color) r g b / <alpha-value>);
  --color-primary-outline: rgb(from var(--mantine-primary-color-outline) r g b / <alpha-value>);
  --color-primary-outline-hover: var(--mantine-primary-color-outline-hover);

  /* colors - others */
  --color-white: rgb(from var(--mantine-color-white) r g b / <alpha-value>);
  --color-black: rgb(from var(--mantine-color-black) r g b / <alpha-value>);
  --color-body: rgb(from var(--mantine-color-text) r g b / <alpha-value>);
  --color-error: rgb(from var(--mantine-color-error) r g b / <alpha-value>);
  --color-placeholder: rgb(from var(--mantine-color-placeholder) r g b / <alpha-value>);
  --color-anchor: rgb(from var(--mantine-color-anchor) r g b / <alpha-value>);
  --color-default: rgb(from var(--mantine-color-default-color) r g b / <alpha-value>);

  /* spacing */
  --spacing-xs: var(--mantine-spacing-xs);
  --spacing-sm: var(--mantine-spacing-sm);
  --spacing-md: var(--mantine-spacing-md);
  --spacing-lg: var(--mantine-spacing-lg);
  --spacing-xl: var(--mantine-spacing-xl);
  --spacing: var(--mantine-spacing-md);

  /* container */
  /* TODO: */

  /* font size */
  --text-xs: var(--mantine-font-size-xs);
  --text-sm: var(--mantine-font-size-sm);
  --text-md: var(--mantine-font-size-md);
  --text-lg: var(--mantine-font-size-lg);
  --text-xl: var(--mantine-font-size-xl);
  --text-h1: var(--mantine-h1-font-size);
  --text-h2: var(--mantine-h2-font-size);
  --text-h3: var(--mantine-h3-font-size);
  --text-h4: var(--mantine-h4-font-size);
  --text-h5: var(--mantine-h5-font-size);
  --text-h6: var(--mantine-h6-font-size);
  --text-base: var(--mantine-font-size-md);

  /* line height */
  --text-xs--line-height: var(--mantine-line-height-xs);
  --text-sm--line-height: var(--mantine-line-height-sm);
  --text-md--line-height: var(--mantine-line-height-md);
  --text-lg--line-height: var(--mantine-line-height-lg);
  --text-xl--line-height: var(--mantine-line-height-xl);
  --text-h1--line-height: var(--mantine-h1-line-height);
  --text-h2--line-height: var(--mantine-h2-line-height);
  --text-h3--line-height: var(--mantine-h3-line-height);
  --text-h4--line-height: var(--mantine-h4-line-height);
  --text-h5--line-height: var(--mantine-h5-line-height);
  --text-h6--line-height: var(--mantine-h6-line-height);
  --text-base--line-height: var(--mantine-line-height-md);
  --text-heading--line-height: var(--mantine-heading-line-height);
  --text-base--line-height: var(--mantine-line-height);

  /* font weight */
  --font-weight-h1: var(--mantine-h1-font-weight);
  --font-weight-h2: var(--mantine-h2-font-weight);
  --font-weight-h3: var(--mantine-h3-font-weight);
  --font-weight-h4: var(--mantine-h4-font-weight);
  --font-weight-h5: var(--mantine-h5-font-weight);
  --font-weight-h6: var(--mantine-h6-font-weight);

  /* border radius */
  --radius-xs: var(--mantine-radius-xs);
  --radius-sm: var(--mantine-radius-sm);
  --radius-md: var(--mantine-radius-md);
  --radius-lg: var(--mantine-radius-lg);
  --radius-xl: var(--mantine-radius-xl);
  --radius: var(--mantine-radius-default);

  /* shadow */
  --shadow-xs: var(--mantine-shadow-xs);
  --shadow-sm: var(--mantine-shadow-sm);
  --shadow-md: var(--mantine-shadow-md);
  --shadow-lg: var(--mantine-shadow-lg);
  --shadow-xl: var(--mantine-shadow-xl);
  --shadow: var(--mantine-shadow-xs);

  /* z-index */
  --z-index-app: var(--mantine-z-index-app);
  --z-index-modal: var(--mantine-z-index-modal);
  --z-index-popover: var(--mantine-z-index-popover);
  --z-index-overlay: var(--mantine-z-index-overlay);
  --z-index-max: var(--mantine-z-index-max);
  `.trimEnd()
			: ""
	}

  /* colors - all */
  ${Object.keys(theme.colors ?? {})
		.map((key) =>
			`
  --color-${key}-50: rgb(from var(--mantine-color-${key}-0) r g b / <alpha-value>);
  --color-${key}-100: rgb(from var(--mantine-color-${key}-1) r g b / <alpha-value>);
  --color-${key}-200: rgb(from var(--mantine-color-${key}-2) r g b / <alpha-value>);
  --color-${key}-300: rgb(from var(--mantine-color-${key}-3) r g b / <alpha-value>);
  --color-${key}-400: rgb(from var(--mantine-color-${key}-4) r g b / <alpha-value>);
  --color-${key}-500: rgb(from var(--mantine-color-${key}-5) r g b / <alpha-value>);
  --color-${key}-600: rgb(from var(--mantine-color-${key}-6) r g b / <alpha-value>);
  --color-${key}-700: rgb(from var(--mantine-color-${key}-7) r g b / <alpha-value>);
  --color-${key}-800: rgb(from var(--mantine-color-${key}-8) r g b / <alpha-value>);
  --color-${key}-900: rgb(from var(--mantine-color-${key}-9) r g b / <alpha-value>);
  --color-${key}: rgb(from var(--mantine-color-${key}-filled) r g b / <alpha-value>);
  `.trimEnd(),
		)
		.join("\n")}

  /* colors - variant specific */
  ${Object.keys(theme.colors ?? {})
		.map((key) =>
			`
  --color-${key}-filled: rgb(from var(--mantine-color-${key}-filled) r g b / <alpha-value>);
  --color-${key}-filled-hover: var(--mantine-color-${key}-filled-hover);
  --color-${key}-light: var(--mantine-color-${key}-light);
  --color-${key}-light-hover: var(--mantine-color-${key}-light-hover);
  --color-${key}-light-color: rgb(from var(--mantine-color-${key}-light-color) r g b / <alpha-value>);
  --color-${key}-outline: rgb(from var(--mantine-color-${key}-outline) r g b / <alpha-value>);
  --color-${key}-outline-hover: var(--mantine-color-${key}-outline-hover);
  `.trimEnd(),
		)
		.join("\n")}

  /* breakpoints */
  ${Object.entries(theme.breakpoints ?? {})
		.map(([key, value]) =>
			`
  --breakpoint-${key}: ${value};
  `.trimEnd(),
		)
		.join("\n")}
}
`;
}
