// for reference:
// https://github.com/mantinedev/mantine/blob/master/packages/%40mantine/core/src/core/MantineProvider/MantineCssVariables/default-css-variables-resolver.ts
// https://github.com/mantinedev/mantine/blob/master/packages/%40mantine/core/src/core/MantineProvider/MantineCssVariables/get-css-color-variables.ts
// https://tailwindcss.com/docs/theme#default-theme-variable-reference

import { DEFAULT_THEME, mergeMantineTheme } from "@mantine/core";

const AUTOGENERATED_COMMENT =
	"/** This file is autogenerated by the script. Do not edit it manually. */\n";
const COLOR_STEPS = [50, 100, 200, 300, 400, 500, 600, 700, 800, 900];
const DEFAULT_CONTAINER_SIZES = [
	["3xs", "16rem"],
	["2xs", "18rem"],
	["xs", "20rem"],
	["sm", "24rem"],
	["md", "28rem"],
	["lg", "32rem"],
	["xl", "36rem"],
	["2xl", "42rem"],
	["3xl", "48rem"],
	["4xl", "56rem"],
	["5xl", "64rem"],
	["6xl", "72rem"],
	["7xl", "80rem"],
];

export function generateDefaultImports() {
	return `${AUTOGENERATED_COMMENT}@layer theme, base, mantine, components, utilities;
@import "tailwindcss/theme.css" layer(theme);
@import "tailwindcss/preflight.css" layer(base);
@import "tailwindcss/utilities.css" layer(utilities);

@import "@mantine/core/styles.layer.css";
`;
}

/**
 * @param {import("@mantine/core").MantineTheme} theme
 */
export function generateTheme(theme = DEFAULT_THEME, options = {}) {
	const { includeComment = true } = options;
	const isDefault = JSON.stringify(theme) === JSON.stringify(DEFAULT_THEME);
	const mergedTheme = mergeMantineTheme(DEFAULT_THEME, theme);

	const colorKeys = Object.keys(mergedTheme.colors ?? {});
	const spacingKeys = Object.keys(mergedTheme.spacing ?? {});
	const fontSizeKeys = Object.keys(mergedTheme.fontSizes ?? {});
	const lineHeightKeys = Object.keys(mergedTheme.lineHeights ?? {});
	const fontWeightKeys = Object.keys(mergedTheme.fontWeights ?? {});
	const radiusKeys = Object.keys(mergedTheme.radius ?? {});
	const shadowKeys = Object.keys(mergedTheme.shadows ?? {});
	const headingKeys = Object.keys(mergedTheme.headings?.sizes ?? {});
	const breakpointEntries = Object.entries(mergedTheme.breakpoints ?? {});
	const primaryColor = mergedTheme.primaryColor;
	const defaultShadowKey = shadowKeys.includes("xs")
		? "xs"
		: (shadowKeys[0] ?? "xs");
	const darkVariant = isDefault
		? `@custom-variant dark (&:where(
		[data-mantine-color-scheme="dark"],
		[data-mantine-color-scheme="dark"] *
	));`
		: "";

	return `${includeComment ? AUTOGENERATED_COMMENT : ""}${darkVariant}

@theme inline {
	/* font */
	--font-sans: var(--mantine-font-family);
	--font-mono: var(--mantine-font-family-monospace);
	--font-headings: var(--mantine-font-family-headings);

	/* colors - primary */
	${COLOR_STEPS.map(
		(step, index) =>
			`--color-primary-${step}: var(--mantine-primary-color-${index});`,
	).join("\n\t")}
	--color-primary: var(--mantine-primary-color-filled);

	/* colors - primary variants */
	--color-primary-text: var(--mantine-color-${primaryColor}-text);
	--color-primary-filled: var(--mantine-primary-color-filled);
	--color-primary-filled-hover: var(--mantine-primary-color-filled-hover);
	--color-primary-light: var(--mantine-primary-color-light);
	--color-primary-light-hover: var(--mantine-primary-color-light-hover);
	--color-primary-light-color: var(--mantine-primary-color-light-color);
	--color-primary-outline: var(--mantine-color-${primaryColor}-outline);
	--color-primary-outline-hover: var(--mantine-color-${primaryColor}-outline-hover);
	--color-primary-contrast: var(--mantine-primary-color-contrast);

	/* colors - others */
	--color-white: var(--mantine-color-white);
	--color-black: var(--mantine-color-black);
	--color-bright: var(--mantine-color-bright);
	--color-body: var(--mantine-color-body);
	--color-text: var(--mantine-color-text);
	--color-error: var(--mantine-color-error);
	--color-placeholder: var(--mantine-color-placeholder);
	--color-anchor: var(--mantine-color-anchor);
	--color-default: var(--mantine-color-default);
	--color-default-hover: var(--mantine-color-default-hover);
	--color-default-color: var(--mantine-color-default-color);
	--color-default-border: var(--mantine-color-default-border);
	--color-dimmed: var(--mantine-color-dimmed);
	--color-disabled: var(--mantine-color-disabled);
	--color-disabled-color: var(--mantine-color-disabled-color);
	--color-disabled-border: var(--mantine-color-disabled-border);

	/* colors - all */
	${colorKeys
		.map((key) =>
			`
	${COLOR_STEPS.map(
		(step, index) =>
			`--color-${key}-${step}: var(--mantine-color-${key}-${index});`,
	).join("\n\t")}
	--color-${key}: var(--mantine-color-${key}-filled);`.trim(),
		)
		.join("\n\t")}

	/* colors - variants */
	${colorKeys
		.map((key) =>
			`
	--color-${key}-text: var(--mantine-color-${key}-text);
	--color-${key}-filled: var(--mantine-color-${key}-filled);
	--color-${key}-filled-hover: var(--mantine-color-${key}-filled-hover);
	--color-${key}-light: var(--mantine-color-${key}-light);
	--color-${key}-light-hover: var(--mantine-color-${key}-light-hover);
	--color-${key}-light-color: var(--mantine-color-${key}-light-color);
	--color-${key}-outline: var(--mantine-color-${key}-outline);
	--color-${key}-outline-hover: var(--mantine-color-${key}-outline-hover);`.trim(),
		)
		.join("\n\t")}

	/* spacing */
	${spacingKeys
		.map((key) => `--spacing-${key}: var(--mantine-spacing-${key});`)
		.join("\n\t")}

	/* font size */
	${fontSizeKeys
		.map((key) => `--text-${key}: var(--mantine-font-size-${key});`)
		.join("\n\t")}
	${headingKeys
		.map((key) => `--text-${key}: var(--mantine-${key}-font-size);`)
		.join("\n\t")}
	--text-base: var(--mantine-font-size-md);

	/* line height */
	${lineHeightKeys
		.map(
			(key) => `--text-${key}--line-height: var(--mantine-line-height-${key});`,
		)
		.join("\n\t")}
	${headingKeys
		.map(
			(key) => `--text-${key}--line-height: var(--mantine-${key}-line-height);`,
		)
		.join("\n\t")}
	--text-base--line-height: var(--mantine-line-height);

	/* font weight */
	${fontWeightKeys
		.map((key) => `--font-weight-${key}: var(--mantine-font-weight-${key});`)
		.join("\n\t")}
	${headingKeys
		.map((key) => `--font-weight-${key}: var(--mantine-${key}-font-weight);`)
		.join("\n\t")}
	--font-weight-heading: var(--mantine-heading-font-weight);

	/* border radius */
	${radiusKeys
		.map((key) => `--radius-${key}: var(--mantine-radius-${key});`)
		.join("\n\t")}
	--radius: var(--mantine-radius-default);

	/* shadow */
	${shadowKeys
		.map((key) => `--shadow-${key}: var(--mantine-shadow-${key});`)
		.join("\n\t")}
	--shadow: var(--mantine-shadow-${defaultShadowKey});

	/* z-index */
	--z-index-app: var(--mantine-z-index-app);
	--z-index-modal: var(--mantine-z-index-modal);
	--z-index-popover: var(--mantine-z-index-popover);
	--z-index-overlay: var(--mantine-z-index-overlay);
	--z-index-max: var(--mantine-z-index-max);

	/* breakpoints */
	${breakpointEntries.length > 0 ? "--breakpoint-*: initial;" : ""}
	${breakpointEntries
		.map(([key, value]) => `--breakpoint-${key}: ${value};`)
		.join("\n\t")}

	/* restore Tailwind container and sizing defaults */
	${DEFAULT_CONTAINER_SIZES.map(
		([key, value]) => `--size-${key}: ${value};`,
	).join("\n\t")}
	${DEFAULT_CONTAINER_SIZES.map(
		([key]) => `--container-${key}: var(--size-${key});`,
	).join("\n\t")}
	${DEFAULT_CONTAINER_SIZES.map(
		([key]) => `--width-${key}: var(--size-${key});`,
	).join("\n\t")}
	${DEFAULT_CONTAINER_SIZES.map(
		([key]) => `--min-width-${key}: var(--size-${key});`,
	).join("\n\t")}
	${DEFAULT_CONTAINER_SIZES.map(
		([key]) => `--max-width-${key}: var(--size-${key});`,
	).join("\n\t")}
	${DEFAULT_CONTAINER_SIZES.map(
		([key]) => `--flex-basis-${key}: var(--size-${key});`,
	).join("\n\t")}
}
`;
}
