// for reference:
// https://github.com/mantinedev/mantine/blob/master/packages/%40mantine/core/src/core/MantineProvider/global.css
// https://tailwindcss.com/docs/theme#default-theme-variable-reference

import { DEFAULT_THEME } from "@mantine/core";

export function generateDefaultImports() {
	return `/** This file is autogenerated by the script. Do not edit it manually. */
@layer theme, base, mantine, components, utilities;
@import "tailwindcss/theme.css" layer(theme);
@import "tailwindcss/preflight.css" layer(base);
@import "tailwindcss/utilities.css" layer(utilities);

@import "@mantine/core/styles.layer.css";
`;
}

/**
 * @param {import("@mantine/core").MantineTheme} theme
 */
export function generateTheme(theme = DEFAULT_THEME) {
	// check if the object is deeply equal to DEFAULT_THEME
	const isDefault = JSON.stringify(theme) === JSON.stringify(DEFAULT_THEME);

	return `/** This file is autogenerated by the script. Do not edit it manually. */
${
	isDefault
		? '@custom-variant dark (&:where([data-mantine-color-scheme="dark"], [data-mantine-color-scheme="dark"] *));'
		: ""
}

@theme {
  ${
		isDefault
			? `
  /* font */
  --font-sans: var(--mantine-font-family);
  --font-mono: var(--mantine-font-family-monospace);
  --font-headings: var(--mantine-font-family-headings);

  /* colors - primary */
  --color-primary-50: var(--mantine-primary-color-0);
  --color-primary-100: var(--mantine-primary-color-1);
  --color-primary-200: var(--mantine-primary-color-2);
  --color-primary-300: var(--mantine-primary-color-3);
  --color-primary-400: var(--mantine-primary-color-4);
  --color-primary-500: var(--mantine-primary-color-5);
  --color-primary-600: var(--mantine-primary-color-6);
  --color-primary-700: var(--mantine-primary-color-7);
  --color-primary-800: var(--mantine-primary-color-8);
  --color-primary-900: var(--mantine-primary-color-9);
  --color-primary: var(--mantine-primary-color-filled);

  /* colors - variant specific primary */
  --color-primary-filled: var(--mantine-primary-color-filled);
  --color-primary-filled-hover: var(--mantine-primary-color-filled-hover);
  --color-primary-light: var(--mantine-primary-color-light);
  --color-primary-light-hover: var(--mantine-primary-color-light-hover);
  --color-primary-light-color: var(--mantine-primary-color-light-color);
  --color-primary-outline: var(--mantine-primary-color-outline);
  --color-primary-outline-hover: var(--mantine-primary-color-outline-hover);
  --color-primary-contrast: var(--mantine-primary-color-contrast);

  /* colors - others */
  --color-white: var(--mantine-color-white);
  --color-black: var(--mantine-color-black);
  --color-bright: var(--mantine-color-bright);
  --color-body: var(--mantine-color-text);
  --color-error: var(--mantine-color-error);
  --color-placeholder: var(--mantine-color-placeholder);
  --color-anchor: var(--mantine-color-anchor);
  --color-default: var(--mantine-color-default);
  --color-default-hover: var(--mantine-color-default-hover);
  --color-default-color: var(--mantine-color-default-color);
  --color-default-border: var(--mantine-color-default-border);
  --color-dimmed: var(--mantine-color-dimmed);
  --color-disabled: var(--mantine-color-disabled);
  --color-disabled-color: var(--mantine-color-disabled-color);
  --color-disabled-border: var(--mantine-color-disabled-border);

  /* spacing */
  --spacing-xs: var(--mantine-spacing-xs);
  --spacing-sm: var(--mantine-spacing-sm);
  --spacing-md: var(--mantine-spacing-md);
  --spacing-lg: var(--mantine-spacing-lg);
  --spacing-xl: var(--mantine-spacing-xl);

  /* font size */
  --text-xs: var(--mantine-font-size-xs);
  --text-sm: var(--mantine-font-size-sm);
  --text-md: var(--mantine-font-size-md);
  --text-lg: var(--mantine-font-size-lg);
  --text-xl: var(--mantine-font-size-xl);
  --text-h1: var(--mantine-h1-font-size);
  --text-h2: var(--mantine-h2-font-size);
  --text-h3: var(--mantine-h3-font-size);
  --text-h4: var(--mantine-h4-font-size);
  --text-h5: var(--mantine-h5-font-size);
  --text-h6: var(--mantine-h6-font-size);
  --text-base: var(--mantine-font-size-md);

  /* line height */
  --text-xs--line-height: var(--mantine-line-height-xs);
  --text-sm--line-height: var(--mantine-line-height-sm);
  --text-md--line-height: var(--mantine-line-height-md);
  --text-lg--line-height: var(--mantine-line-height-lg);
  --text-xl--line-height: var(--mantine-line-height-xl);
  --text-h1--line-height: var(--mantine-h1-line-height);
  --text-h2--line-height: var(--mantine-h2-line-height);
  --text-h3--line-height: var(--mantine-h3-line-height);
  --text-h4--line-height: var(--mantine-h4-line-height);
  --text-h5--line-height: var(--mantine-h5-line-height);
  --text-h6--line-height: var(--mantine-h6-line-height);
  --text-base--line-height: var(--mantine-line-height-md);
  --text-heading--line-height: var(--mantine-heading-line-height);
  --text-base--line-height: var(--mantine-line-height);

  /* font weight */
  --font-weight-h1: var(--mantine-h1-font-weight);
  --font-weight-h2: var(--mantine-h2-font-weight);
  --font-weight-h3: var(--mantine-h3-font-weight);
  --font-weight-h4: var(--mantine-h4-font-weight);
  --font-weight-h5: var(--mantine-h5-font-weight);
  --font-weight-h6: var(--mantine-h6-font-weight);

  /* border radius */
  --radius-xs: var(--mantine-radius-xs);
  --radius-sm: var(--mantine-radius-sm);
  --radius-md: var(--mantine-radius-md);
  --radius-lg: var(--mantine-radius-lg);
  --radius-xl: var(--mantine-radius-xl);
  --radius: var(--mantine-radius-default);

  /* shadow */
  --shadow-xs: var(--mantine-shadow-xs);
  --shadow-sm: var(--mantine-shadow-sm);
  --shadow-md: var(--mantine-shadow-md);
  --shadow-lg: var(--mantine-shadow-lg);
  --shadow-xl: var(--mantine-shadow-xl);
  --shadow: var(--mantine-shadow-xs);

  /* z-index */
  --z-index-app: var(--mantine-z-index-app);
  --z-index-modal: var(--mantine-z-index-modal);
  --z-index-popover: var(--mantine-z-index-popover);
  --z-index-overlay: var(--mantine-z-index-overlay);
  --z-index-max: var(--mantine-z-index-max);
  `.trimEnd()
			: ""
	}

  /* colors - all */
  ${Object.keys(theme.colors ?? {})
		.map((key) =>
			`
  --color-${key}-50: var(--mantine-color-${key}-0);
  --color-${key}-100: var(--mantine-color-${key}-1);
  --color-${key}-200: var(--mantine-color-${key}-2);
  --color-${key}-300: var(--mantine-color-${key}-3);
  --color-${key}-400: var(--mantine-color-${key}-4);
  --color-${key}-500: var(--mantine-color-${key}-5);
  --color-${key}-600: var(--mantine-color-${key}-6);
  --color-${key}-700: var(--mantine-color-${key}-7);
  --color-${key}-800: var(--mantine-color-${key}-8);
  --color-${key}-900: var(--mantine-color-${key}-9);
  --color-${key}: var(--mantine-color-${key}-filled);
  `.trimEnd(),
		)
		.join("\n")}

  /* colors - variant specific */
  ${Object.keys(theme.colors ?? {})
		.map((key) =>
			`
  --color-${key}-filled: var(--mantine-color-${key}-filled);
  --color-${key}-filled-hover: var(--mantine-color-${key}-filled-hover);
  --color-${key}-light: var(--mantine-color-${key}-light);
  --color-${key}-light-hover: var(--mantine-color-${key}-light-hover);
  --color-${key}-light-color: var(--mantine-color-${key}-light-color);
  --color-${key}-outline: var(--mantine-color-${key}-outline);
  --color-${key}-outline-hover: var(--mantine-color-${key}-outline-hover);
  `.trimEnd(),
		)
		.join("\n")}

  /* breakpoints */
  ${theme.breakpoints ? "--breakpoint-*: initial;" : ""}
${Object.entries(theme.breakpoints ?? {})
	.map(([key, value]) =>
		`  --breakpoint-${key}: ${value};
  `.trimEnd(),
	)
	.join("\n")}

  /* read back tailwind's default containers vars to fix #24 */
  --size-3xs: 16rem;
  --size-2xs: 18rem;
  --size-xs: 20rem;
  --size-sm: 24rem;
  --size-md: 28rem;
  --size-lg: 32rem;
  --size-xl: 36rem;
  --size-2xl: 42rem;
  --size-3xl: 48rem;
  --size-4xl: 56rem;
  --size-5xl: 64rem;
  --size-6xl: 72rem;
  --size-7xl: 80rem;

  --container-3xs: var(--size-3xs);
  --container-2xs: var(--size-2xs);
  --container-xs: var(--size-xs);
  --container-sm: var(--size-sm);
  --container-md: var(--size-md);
  --container-lg: var(--size-lg);
  --container-xl: var(--size-xl);
  --container-2xl: var(--size-2xl);
  --container-3xl: var(--size-3xl);
  --container-4xl: var(--size-4xl);
  --container-5xl: var(--size-5xl);
  --container-6xl: var(--size-6xl);
  --container-7xl: var(--size-7xl);

  --width-3xs: var(--size-3xs);
  --width-2xs: var(--size-2xs);
  --width-xs: var(--size-xs);
  --width-sm: var(--size-sm);
  --width-md: var(--size-md);
  --width-lg: var(--size-lg);
  --width-xl: var(--size-xl);
  --width-2xl: var(--size-2xl);
  --width-3xl: var(--size-3xl);
  --width-4xl: var(--size-4xl);
  --width-5xl: var(--size-5xl);
  --width-6xl: var(--size-6xl);
  --width-7xl: var(--size-7xl);

  --min-width-3xs: var(--size-3xs);
  --min-width-2xs: var(--size-2xs);
  --min-width-xs: var(--size-xs);
  --min-width-sm: var(--size-sm);
  --min-width-md: var(--size-md);
  --min-width-lg: var(--size-lg);
  --min-width-xl: var(--size-xl);
  --min-width-2xl: var(--size-2xl);
  --min-width-3xl: var(--size-3xl);
  --min-width-4xl: var(--size-4xl);
  --min-width-5xl: var(--size-5xl);
  --min-width-6xl: var(--size-6xl);
  --min-width-7xl: var(--size-7xl);

  --max-width-3xs: var(--size-3xs);
  --max-width-2xs: var(--size-2xs);
  --max-width-xs: var(--size-xs);
  --max-width-sm: var(--size-sm);
  --max-width-md: var(--size-md);
  --max-width-lg: var(--size-lg);
  --max-width-xl: var(--size-xl);
  --max-width-2xl: var(--size-2xl);
  --max-width-3xl: var(--size-3xl);
  --max-width-4xl: var(--size-4xl);
  --max-width-5xl: var(--size-5xl);
  --max-width-6xl: var(--size-6xl);
  --max-width-7xl: var(--size-7xl);

  --height-3xs: var(--size-3xs);
  --height-2xs: var(--size-2xs);
  --height-xs: var(--size-xs);
  --height-sm: var(--size-sm);
  --height-md: var(--size-md);
  --height-lg: var(--size-lg);
  --height-xl: var(--size-xl);
  --height-2xl: var(--size-2xl);
  --height-3xl: var(--size-3xl);
  --height-4xl: var(--size-4xl);
  --height-5xl: var(--size-5xl);
  --height-6xl: var(--size-6xl);
  --height-7xl: var(--size-7xl);

  --min-height-3xs: var(--size-3xs);
  --min-height-2xs: var(--size-2xs);
  --min-height-xs: var(--size-xs);
  --min-height-sm: var(--size-sm);
  --min-height-md: var(--size-md);
  --min-height-lg: var(--size-lg);
  --min-height-xl: var(--size-xl);
  --min-height-2xl: var(--size-2xl);
  --min-height-3xl: var(--size-3xl);
  --min-height-4xl: var(--size-4xl);
  --min-height-5xl: var(--size-5xl);
  --min-height-6xl: var(--size-6xl);
  --min-height-7xl: var(--size-7xl);

  --max-height-3xs: var(--size-3xs);
  --max-height-2xs: var(--size-2xs);
  --max-height-xs: var(--size-xs);
  --max-height-sm: var(--size-sm);
  --max-height-md: var(--size-md);
  --max-height-lg: var(--size-lg);
  --max-height-xl: var(--size-xl);
  --max-height-2xl: var(--size-2xl);
  --max-height-3xl: var(--size-3xl);
  --max-height-4xl: var(--size-4xl);
  --max-height-5xl: var(--size-5xl);
  --max-height-6xl: var(--size-6xl);
  --max-height-7xl: var(--size-7xl);
}
`;
}
